### ISSUE TITLE
Launch IGS execution engine without the default agent's name fail

### ISSUE THREAD

**Issue by Fafou** [zeromq/ingescape#25]
Hello,

I'm trying to use Ingescape with a multi agent program.

I'm working on C++ so I start to create a C++ binding to IGS agent, but I think that it's not a problem.
Conceptually the software architecture it's really simple:

1. Initiallise all my IGS agents
2. Launch IGS execution engine for my platform/program
3. Launch all my agents's processing

I made a small example to show the "problem": https://gist.github.com/Fafou/cd1f87140588b6ed5cd6a8d6d51a3f48
(I build this example with: g++ -std=c++17 -o testAgent testAgents.cpp -lingescape -lczmq -lpthread)

Today it didn't work because I didn't "manage" the internal IGS agent in addition to my agents.
Without setting a name to the internal agent, IGS do not start.
(a small comment in this example, after "igs_start_with_device",  explains the cause of the problem)

For me, but I could be wrong, IGS execution engine do not need to create a default agent if user use it's own agents.

If user use default functions like: igs_input_create, in that case, yes he didn't want to manage it's own agent, so IGS can create agent for him, it's the "easy way" to use IGS. But if user want to manage its own agents by using igsagent_input_create, in that case we just need a valid IGS context, without default agent.

do you agree with my analysis? or am I the one who is using this library incorrectly ?

**Comment by stvales** [comment]
The crash is due to a faulty chain of init for core_agent. We solved it by editing igsagent_set_name to properly init core_agent private channel even if its name is already set to default, which is the case when it is initialized by using logs before starting ingescape.
As a reminder, core_agent is mandatory at this stage because it carries the underlying zyre node. That is why we do not expose the ingescape context yet and do not allow the creation of additional agents without a default one.
